version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Puerto 80 dentro del contenedor (Nginx) será mapeado al puerto 3000 del host
    networks:
      - red-inscribcordoba

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Puerto 4000 del backend será mapeado al mismo puerto en el host
    networks:
      - red-inscribcordoba
    
networks:
  red-inscribcordoba:
    driver: bridge
